// Team-Hilfen: Flaggen-Emojis + Übersetzung englischer API-Namen (football-data.org)
// auf deutsche Anzeigenamen. Beide Maps decken Deutsch UND Englisch ab, damit
// Fallback-Schedule (Deutsch) und Live-Import (Englisch) funktionieren.

// Englischer API-Name → deutscher Anzeigename.
const TEAM_DE: Record<string, string> = {
  'Austria': 'Österreich',
  'Germany': 'Deutschland',
  'France': 'Frankreich',
  'Spain': 'Spanien',
  'England': 'England',
  'Portugal': 'Portugal',
  'Netherlands': 'Niederlande',
  'Belgium': 'Belgien',
  'Italy': 'Italien',
  'Croatia': 'Kroatien',
  'Switzerland': 'Schweiz',
  'Denmark': 'Dänemark',
  'Poland': 'Polen',
  'Serbia': 'Serbien',
  'Ukraine': 'Ukraine',
  'Turkey': 'Türkei',
  'Türkiye': 'Türkei',
  'Scotland': 'Schottland',
  'Wales': 'Wales',
  'Hungary': 'Ungarn',
  'Romania': 'Rumänien',
  'Slovakia': 'Slowakei',
  'Greece': 'Griechenland',
  'Georgia': 'Georgien',
  'Czech Republic': 'Tschechien',
  'Czechia': 'Tschechien',
  'Albania': 'Albanien',
  'Slovenia': 'Slowenien',
  'Finland': 'Finnland',
  'Sweden': 'Schweden',
  'Norway': 'Norwegen',
  'Iceland': 'Island',
  'Republic of Ireland': 'Irland',
  'Ireland': 'Irland',
  'Kosovo': 'Kosovo',
  'North Macedonia': 'Nordmazedonien',
  'Bosnia and Herzegovina': 'Bosnien',
  'Bosnia-Herzegovina': 'Bosnien',
  'Russia': 'Russland',
  'United States': 'USA',
  'USA': 'USA',
  'Mexico': 'Mexiko',
  'Canada': 'Kanada',
  'Costa Rica': 'Costa Rica',
  'Panama': 'Panama',
  'Honduras': 'Honduras',
  'Jamaica': 'Jamaika',
  'El Salvador': 'El Salvador',
  'Cuba': 'Kuba',
  'Guatemala': 'Guatemala',
  'Haiti': 'Haiti',
  'Trinidad and Tobago': 'Trinidad und Tobago',
  'Curaçao': 'Curacao',
  'Curacao': 'Curacao',
  'Brazil': 'Brasilien',
  'Argentina': 'Argentinien',
  'Colombia': 'Kolumbien',
  'Ecuador': 'Ecuador',
  'Uruguay': 'Uruguay',
  'Chile': 'Chile',
  'Peru': 'Peru',
  'Paraguay': 'Paraguay',
  'Bolivia': 'Bolivien',
  'Venezuela': 'Venezuela',
  'Morocco': 'Marokko',
  'Senegal': 'Senegal',
  'Nigeria': 'Nigeria',
  'Cameroon': 'Kamerun',
  'Ghana': 'Ghana',
  'Mali': 'Mali',
  'Egypt': 'Ägypten',
  'Algeria': 'Algerien',
  'Tunisia': 'Tunesien',
  'South Africa': 'Südafrika',
  "Côte d'Ivoire": 'Elfenbeinküste',
  'Ivory Coast': 'Elfenbeinküste',
  'Cape Verde': 'Kap Verde',
  'Cabo Verde': 'Kap Verde',
  'Angola': 'Angola',
  'DR Congo': 'Kongo DR',
  'Congo DR': 'Kongo DR',
  'Congo': 'Kongo',
  'Tanzania': 'Tansania',
  'Japan': 'Japan',
  'South Korea': 'Südkorea',
  'Korea Republic': 'Südkorea',
  'Iran': 'Iran',
  'Saudi Arabia': 'Saudi-Arabien',
  'Australia': 'Australien',
  'New Zealand': 'Neuseeland',
  'Uzbekistan': 'Usbekistan',
  'Qatar': 'Katar',
  'Jordan': 'Jordanien',
  'Iraq': 'Irak',
  'China PR': 'China',
  'China': 'China',
  'Indonesia': 'Indonesien',
  'Oman': 'Oman',
  'Bahrain': 'Bahrain',
  'Kuwait': 'Kuwait',
};

// Deutscher Anzeigename → Flagge. (Wir übersetzen erst, dann eine Map.)
const FLAGS_DE: Record<string, string> = {
  'Österreich': '🇦🇹', 'Deutschland': '🇩🇪', 'Frankreich': '🇫🇷', 'Spanien': '🇪🇸',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Portugal': '🇵🇹', 'Niederlande': '🇳🇱', 'Belgien': '🇧🇪',
  'Italien': '🇮🇹', 'Kroatien': '🇭🇷', 'Schweiz': '🇨🇭', 'Dänemark': '🇩🇰',
  'Polen': '🇵🇱', 'Serbien': '🇷🇸', 'Ukraine': '🇺🇦', 'Türkei': '🇹🇷',
  'Schottland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿', 'Ungarn': '🇭🇺', 'Rumänien': '🇷🇴',
  'Slowakei': '🇸🇰', 'Griechenland': '🇬🇷', 'Georgien': '🇬🇪', 'Tschechien': '🇨🇿',
  'Albanien': '🇦🇱', 'Slowenien': '🇸🇮', 'Finnland': '🇫🇮', 'Schweden': '🇸🇪',
  'Norwegen': '🇳🇴', 'Island': '🇮🇸', 'Irland': '🇮🇪', 'Kosovo': '🇽🇰',
  'Nordmazedonien': '🇲🇰', 'Bosnien': '🇧🇦', 'Russland': '🇷🇺',
  'USA': '🇺🇸', 'Mexiko': '🇲🇽', 'Kanada': '🇨🇦', 'Costa Rica': '🇨🇷',
  'Panama': '🇵🇦', 'Honduras': '🇭🇳', 'Jamaika': '🇯🇲', 'El Salvador': '🇸🇻',
  'Kuba': '🇨🇺', 'Guatemala': '🇬🇹', 'Haiti': '🇭🇹', 'Trinidad und Tobago': '🇹🇹',
  'Curacao': '🇨🇼',
  'Brasilien': '🇧🇷', 'Argentinien': '🇦🇷', 'Kolumbien': '🇨🇴', 'Ecuador': '🇪🇨',
  'Uruguay': '🇺🇾', 'Chile': '🇨🇱', 'Peru': '🇵🇪', 'Paraguay': '🇵🇾',
  'Bolivien': '🇧🇴', 'Venezuela': '🇻🇪',
  'Marokko': '🇲🇦', 'Senegal': '🇸🇳', 'Nigeria': '🇳🇬', 'Kamerun': '🇨🇲',
  'Ghana': '🇬🇭', 'Mali': '🇲🇱', 'Ägypten': '🇪🇬', 'Algerien': '🇩🇿',
  'Tunesien': '🇹🇳', 'Südafrika': '🇿🇦', 'Elfenbeinküste': '🇨🇮',
  'Kap Verde': '🇨🇻', 'Cabo Verde': '🇨🇻', 'Cape Verde': '🇨🇻',
  'Angola': '🇦🇴', 'Kongo DR': '🇨🇩', 'Kongo': '🇨🇬', 'Tansania': '🇹🇿',
  'Japan': '🇯🇵', 'Südkorea': '🇰🇷', 'Iran': '🇮🇷', 'Saudi-Arabien': '🇸🇦',
  'Australien': '🇦🇺', 'Neuseeland': '🇳🇿', 'Usbekistan': '🇺🇿', 'Katar': '🇶🇦',
  'Jordanien': '🇯🇴', 'Irak': '🇮🇶', 'China': '🇨🇳', 'Indonesien': '🇮🇩',
  'Oman': '🇴🇲', 'Bahrain': '🇧🇭', 'Kuwait': '🇰🇼',
  // Fallback-Platzhalter
  'Mexiko B': '🇲🇽', 'Niederlande B': '🇳🇱', 'USA B': '🇺🇸',
};

// Englischen oder deutschen Namen → deutscher Anzeigename.
export const deName = (team: string): string => TEAM_DE[team] ?? team;

// Flagge für einen Team-Namen (egal ob Deutsch oder Englisch).
export const flag = (team: string): string => {
  const de = deName(team);
  return FLAGS_DE[de] ?? FLAGS_DE[team] ?? '🏴';
};

export const isAustriaTeam = (name: string): boolean =>
  name === 'Österreich' || name.toLowerCase() === 'austria';
